config/routes.rb
Rails.application.routes.draw do
  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    root to: 'home#index'

    namespace :users do
      resource :profile, only: :show
      resource :invite_people, path: 'invite-people', only: :show
      resources :addresses
      resources :lotteries
      resources :offers, path: 'shop', only: :index do
        post :order
      end
      resources :winners, only: [:show, :update]
      resources :shares, only: [:show, :update]
      resources :feedbacks, only: [:show, :index]
      scope  :orders, path: 'orders', as: 'orders' do
        put "cancel/:order_id", to: 'orders#cancel'
      end
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      root to: 'dashboards#index'

      resources :users, only: :index do
        resources :increases, path: 'orders/increase', only: [:new, :create]
        resources :deducts, path: 'orders/deduct', only: [:new, :create]
        resources :bonuses, path: 'orders/bonus', only: [:new, :create]
      end
      resources :items, path: 'items-list', except: :show do
        put :start, :pause, :end, :cancel
      end
      resources :categories, except: :show
      resources :bets, path: 'bets-list', only: :index do
        put :cancel
      end
      resources :winners, path: 'winners-list', only: :index do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers, path: 'offers-list', except: :show
      resources :orders, path: 'orders-list', only: :index do
        put :pay, :cancel
      end
      resources :invites, path: 'invites-list', only: :index
      resources :news_tickers, path: 'news-ticker', except: :show
      resources :banners, path: 'banners-list', except: :show
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, phone: {allow_blank: true}
  has_many :addresses
  belongs_to :parent,  class_name: "User",counter_cache: :children_members, optional: true
  has_many :children, class_name: "User" , foreign_key: :parent_id
  has_many :bets
  has_many :winners

  def admin?
    role == 'admin'
  end

  def client?
    role == 'client'
  end

  mount_uploader :image, ImageUploader
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.where(role: :client)
    if params['email'].present?
      @users = @users.where(email: params['email'])
    end
  end
end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController
  before_action :set_address, only: [:edit, :update, :destroy]

  def index
    @addresses = current_user.addresses.includes(:region, :province, :city, :barangay).order(id: :desc)
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user

    if @address.save
      flash[:notice] = "Successfully Created"
      redirect_to users_addresses_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      flash[:notice] = "Successfully Updated"
      redirect_to users_addresses_path
    else
      render :edit
    end
  end

  def destroy
    if @address.destroy
      flash[:notice] = "Successfully deleted"
      redirect_to users_addresses_path
    end
  end

  private

  def set_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:name, :phone_number, :street_address, :genre, :region_id, :province_id, :city_id, :barangay_id, :remark, :is_default)
  end
end

app/controllers/users/feedbacks_controller.rb
class Users::FeedbacksController < ApplicationController
  before_action :set_winner, only: :show

  def index
    @winners = Winner.includes(:user).published.order(id: :desc)
  end

  def show; end

  private

  def set_winner
    @winner = Winner.find(params[:id])
  end
end

app/controllers/users/invite_people_controller.rb
class Users::InvitePeopleController < ApplicationController
  before_action :set_url
  before_action :render_qr_code

  def show; end

  private

  def set_url
    if current_user
      @url="#{request.base_url}/users/sign_up?promoter=#{current_user&.email}"
    else
      @url="#{request.base_url}/users/sign_up"
      end
  end

  def render_qr_code
    qrcode = RQRCode::QRCode.new(@url)
    @svg = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 8,
      standalone: true,
      use_path: true
    )
  end
end

app/controllers/users/lotteries_controller.rb
class Users::LotteriesController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :set_item, only: :create

  def index
    @items = Item.active.starting
    @items = @items.includes(:category).where(category: { name: params[:category] }) if params[:category].present?
    @categories = Category.all
  end

  def show
    @item = Item.active.starting.find(params[:id])
    @user_bets = @item.bets.where(user: current_user).where(batch_count: @item.batch_count).betting
    @bet = Bet.new
  end

  def create
    if current_user.coins >= params[:bet][:coins].to_i
      begin
        loop_count = params[:bet][:coins].to_i
        params[:bet][:coins] = 1
        params[:bet][:item_id] = @item
        ActiveRecord::Base.transaction do
          loop_count.times do
            @bet = Bet.new(bet_params)
            @bet.item = @item
            @bet.user = current_user
            @bet.batch_count = @item.batch_count
            @bet.save!
          end
        end
        flash[:notice] = "Bet successfully "
      rescue ActiveRecord::RecordInvalid => exception
        flash[:alert] = exception
      end
      redirect_to users_lottery_path(@item)
      else
        flash[:alert] = "Your coins is #{current_user.coins}, it is insufficient for your bet. Buy coins and bet again!"
      redirect_to users_lottery_path(@item)
    end
  end

  private

  def set_item
    @item = Item.find(params[:bet][:item_id])
  end

  def bet_params
    params.require(:bet).permit(:coins, :item_id)
  end
end

app/controllers/users/offers_controller.rb
class Users::OffersController < ApplicationController
  before_action :set_order, only: :order
  before_action :authenticate_user!, only: :order

  def index
    @offers = Offer.active
  end

  def order
    @order = Order.new
    @order.genre = :deposit
    @order.amount = @offer.amount
    @order.coin = @offer.coin
    @order.user = current_user
    @order.offer = @offer
    if @order.save
      if @order.may_submit? && @order.submit!
        flash[:notice] = "Ordered successfully"
      else
        flash[:alert] = "Ordered failed"
        @order.cancel!
      end
      redirect_to users_offers_path
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
      render :index
    end
  end

  private

  def set_order
    @offer = Offer.active.find(params[:offer_id])
  end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
  before_action :set_order

  def cancel
    if @order.cancel!
      flash[:notice] = "Cancelled Successfully"
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to users_profile_path
  end

  private

  def set_order
    @order = Order.where(user: current_user).submitted.find(params[:order_id])
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  def show
    @orders = Order.where(user: current_user).order(id: :desc) if params[:records] == 'order' || params[:records].blank?
    @bets = Bet.includes(:item).where(user: current_user).order(id: :desc) if params[:records] == 'bet'
    @winners = Winner.includes(:item, :bet).where(user: current_user).order(id: :desc) if params[:records] == 'winner'
    @invites = User.where(parent: current_user).order(id: :desc) if params[:records] == 'invite'
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
    unless cookies[:promoter]
      cookies[:promoter] = params[:promoter]
    end
  end

  def update
    user=params[:user]
    if user[:current_password].blank? && user[:password_confirmation].blank? && user[:password].blank?
      update_user
    else
      update_password
    end
  end

  def create
    params[:user][:parent_id] = User.find_by_email(cookies[:promoter])&.id
    super
  end

  private

  def sign_up_params
    params.require(:user).permit(:parent_id, :email, :password, :password_confirmation, :current_password)
  end

  def update_password
    if @user.update_with_password(user_password_params)
      flash[:notice] = "Successfully Updated"
      sign_in @user, :bypass => true
      redirect_to users_profile_path
    else
      render :edit
    end
  end

  def update_user
    if @user.update(user_details_params)
      flash[:notice] = "Successfully Updated"
      sign_in @user, :bypass => true
      redirect_to users_profile_path
    else
      render :edit
    end
  end

  def user_details_params
    params.require(:user).permit(:phone, :image, :username)
  end

  def user_password_params
    params.require(:user).permit(:phone, :image, :username, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    user = User.find_for_authentication(email: params[:user][:email])
    if user&.admin? && user&.valid_password?(params[:user][:password])
      flash[:notice] = "You don't have permission"
      redirect_to action: :new
    else
      super
    end
  end
end

app/controllers/users/shares_controller.rb
class Users::SharesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner

  def show; end

  def update
    if @winner.update(winner_params) && @winner.share!
      flash[:notice] = "Shared Feedback Successfully !"
      redirect_to users_profile_path(records: :winner)
    else
      flash[:alert] = @winner.errors.full_messages.join(', ') || 'Failed'
      render :show
    end
  end

  private

  def set_winner
    @winner = Winner.where(user: current_user).delivered.find(params[:id])
  end

  def winner_params
    params.require(:winner).permit(:comment, :picture)
  end
end

app/controllers/users/winners_controller.rb
class Users::WinnersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner
  before_action :set_address, only: :update

  def show; end

  def update
    if @winner.update(address: @address) && @winner.claim!
      flash[:notice] = "Claimed Successfully !"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ') || 'Failed'
    end
    redirect_to users_profile_path(records: :winner)
  end

  private

  def set_winner
    @winner = Winner.where(user: current_user).won.find(params[:id])
  end

  def set_address
    @address = current_user.addresses.find(params[:winner][:address])
  end
end

app/helpers/users/lottery_helper.rb
module Users::LotteryHelper
  def progress(item)
    batch = item.bets.where(batch_count: item.batch_count).betting.count
    minimum_bets = item.minimum_bets
    [(batch/minimum_bets) * 100, 100].min.to_i
  end
end

app/views/users/addresses/_form.html.erb
<div class="row">
  <div class="col">
    <div class="form-outline mb-4 text-center">
      <%= f.text_field :name, class: "form-control shadow-sm", placeholder: "Full name", autofocus: true, autocomplete: "username" %>
    </div>
  </div>
  <div class="col">
    <div class="form-outline mb-4 text-center">
      <%= f.text_field :phone_number, class: "form-control shadow-sm", placeholder: "Phone Number", autofocus: true, autocomplete: "phone" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="form-outline mb-4 text-center">
      <%= f.text_field :street_address, class: "form-control shadow-sm", placeholder: "Street Address", autofocus: true, autocomplete: "phone" %>
    </div>
  </div>
  <div class="col">
    <div class="form-outline mb-4 text-center">
      <%= f.select(:genre, Address.genres.keys.map { |key| [key.humanize, key] }, { include_blank: "Genre" }, { class: "form-control shadow-sm" }) %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="form-outline mb-4 text-center">
      <%= f.collection_select :region_id, Region.order(:id), :id, :name, { include_blank: "Please Select Region" }, { class: "form-control shadow-sm" } %>
    </div>
  </div>
  <div class="col">
    <div class="form-outline mb-4 text-center">
      <%= f.collection_select :province_id, Province.order(:id), :id, :name, { include_blank: "Please Select Province" }, { class: "form-control shadow-sm" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="form-outline mb-4 text-center">
      <%= f.collection_select :city_id, City.order(:id), :id, :name, { include_blank: "Please Select city" }, { class: "form-control shadow-sm" } %>
    </div>
  </div>
  <div class="col">
    <div class="form-outline mb-4 text-center">
      <%= f.collection_select :barangay_id, Barangay.where('id<=?', 10).order(:id), :id, :name, { include_blank: "Please Select Barangay" }, { class: "form-control shadow-sm" } %>
    </div>
  </div>
</div>
<%= f.text_area :remark, class: "form-control shadow-sm", :cols => 30, :rows => 2 %>

app/views/users/addresses/edit.html.erb
<%= render "users/shared/nav" %>
<div class="container py-5 h-100 mt-5">
  <%= render "shared/error", resource: @address%>
  <div class="card bg-light w-100 mt-5 shadow rounded border-light">
    <div class="mt-md-4">
      <%= form_for @address, url: users_address_path(@address), method: :patch do |f| %>
        <div class="container">
          <div class="row mb-4">
            <div class="col">
              <%= link_to "Back", users_addresses_path, class: "btn btn-warning px-5 form-control shadow-sm" %>
            </div>
            <div class="col">
              <h2 class="fw-bold mb-3 text-uppercase text-center" style="color:Orange;">Edit</h2>
            </div>
          </div>
        </div>
        <div class="card w-100 mt-1 border-light">
          <div class="card-body shadow-sm">
            <div class="form-outline mb-1">
              <%= render "form", f: f %>
              <% if @address.is_default %>
                <%= f.check_box :is_default, onclick: "return false;", checked: true  %>
              <% else %>
                <%= f.check_box :is_default %>
              <% end %>
              <%= f.label :Default %>
            </div>
            <div class="pt-1 mb-4 text-center">
              <%= f.submit "Update", data: { confirm: 'Are you sure you want to update?' }, class: "btn btn-success px-5 shadow-sm" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/addresses/index.html.erb
<%= render "users/shared/nav" %>
<div class="container py-5 h-100 mt-5 mb-5">
  <%= render "shared/flash_error" %>
  <div class="card bg-light w-100 mt-5 shadow rounded border-light">
    <div class="mb-md-2 mt-md-4 pb-1">
      <div class="container">
        <div class="row p-2">
          <div class="col">
            <%= link_to "Back", users_profile_path, class: "btn btn-warning px-5 form-control shadow-sm" %>
          </div>
          <div class="col">
            <%= link_to "New", new_users_address_path, class: "btn btn-warning px-5 form-control shadow-sm" %>
          </div>
        </div>
        <% if current_user.addresses.blank? %>
          <div class="card w-100">
            <div class="card-body ">
              <p class="card-text text-black text-center">No Address to show</p>
            </div>
          </div>
        <% end %>
        <% @addresses.each do |address| %>
          <div class="card w-100 mt-3 shadow-sm border-light">
            <div class="card-body">
              <div class="row">
                <b><%= content_tag :div, address.genre, class: "badge bg-primary mb-3" %> &nbsp; <%= content_tag :div, 'Default', class: "badge bg-danger" if address.is_default %></b>
                <p class="card-text"><b>Full name:</b> <%= address.name %></p>
                <p class="card-text"><b>Phone Number:</b> <%= address.phone_number %></p>
                <p class="card-text"><b>Address:</b> <%= concat_address(address)%></p>
              </div>
              <div class="d-flex justify-content-start mt-3 mb-2">
                <%= link_to "Edit", edit_users_address_path(address), class: "btn btn-sm btn-success shadow-sm mx-3 px-3" %>
                <%= link_to 'Delete', users_address_path(address), method: :delete, data: { confirm:'Are you sure you want to delete?' },class: "btn btn-sm btn-danger shadow-sm mx-3 px-3" unless address.is_default %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/addresses/new.html.erb
<%= render "users/shared/nav" %>
<div class="container py-5 h-100 mt-5">
  <%= render "shared/error", resource: @address%>
  <div class="card bg-light w-100 mt-5 shadow rounded border-light">
    <div class="mt-md-4 ">
      <%= form_for @address, url: users_addresses_path, method: :post do |f| %>
        <div class="container">
          <div class="row mb-4">
            <div class="col">
              <%= link_to "Back", users_addresses_path, class: "btn btn-warning px-5 form-control" %>
            </div>
            <div class="col">
              <h2 class="fw-bold mb-3 text-uppercase text-center" style="color:Orange;">New</h2>
            </div>
          </div>
        </div>
        <div class="card w-100 mt-1 border-light shadow-sm">
          <div class="card-body">
            <div class="form-outline mb-1">
              <%= render "form", f: f %>
              <%= f.check_box :is_default %>
              <%= f.label :Default %>
              <div class="pt-1 mb-4 text-center">
                <%= f.submit "Create", class: "btn btn-success px-5" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>