config/routes.rb
Rails.application.routes.draw do
  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    root to: 'home#index'

    namespace :users do
      resource :profile, only: :show
      resource :invite_people, path: 'invite-people', only: :show
      resources :addresses
      resources :lotteries
      resources :offers, path: 'shop', only: :index do
        post :order
      end
      resources :winners, only: [:show, :update]
      resources :shares, only: [:show, :update]
      resources :feedbacks, only: [:show, :index]
      scope  :orders, path: 'orders', as: 'orders' do
        put "cancel/:order_id", to: 'orders#cancel'
      end
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      root to: 'dashboards#index'

      resources :users, only: :index do
        resources :increases, path: 'orders/increase', only: [:new, :create]
        resources :deducts, path: 'orders/deduct', only: [:new, :create]
        resources :bonuses, path: 'orders/bonus', only: [:new, :create]
      end
      resources :items, path: 'items-list', except: :show do
        put :start, :pause, :end, :cancel
      end
      resources :categories, except: :show
      resources :bets, path: 'bets-list', only: :index do
        put :cancel
      end
      resources :winners, path: 'winners-list', only: :index do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers, path: 'offers-list', except: :show
      resources :orders, path: 'orders-list', only: :index do
        put :pay, :cancel
      end
      resources :invites, path: 'invites-list', only: :index
      resources :news_tickers, path: 'news-ticker', except: :show
      resources :banners, path: 'banners-list', except: :show
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :phone, phone: {allow_blank: true}
  has_many :addresses
  belongs_to :parent,  class_name: "User",counter_cache: :children_members, optional: true
  has_many :children, class_name: "User" , foreign_key: :parent_id
  has_many :bets
  has_many :winners

  def admin?
    role == 'admin'
  end

  def client?
    role == 'client'
  end

  mount_uploader :image, ImageUploader
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.where(role: :client)
    if params['email'].present?
      @users = @users.where(email: params['email'])
    end
  end
end

app/controllers/users/addresses_controller.rb
class Users::AddressesController < ApplicationController
  before_action :set_address, only: [:edit, :update, :destroy]

  def index
    @addresses = current_user.addresses.includes(:region, :province, :city, :barangay).order(id: :desc)
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user

    if @address.save
      flash[:notice] = "Successfully Created"
      redirect_to users_addresses_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      flash[:notice] = "Successfully Updated"
      redirect_to users_addresses_path
    else
      render :edit
    end
  end

  def destroy
    if @address.destroy
      flash[:notice] = "Successfully deleted"
      redirect_to users_addresses_path
    end
  end

  private

  def set_address
    @address = Address.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:name, :phone_number, :street_address, :genre, :region_id, :province_id, :city_id, :barangay_id, :remark, :is_default)
  end
end

app/controllers/users/feedbacks_controller.rb
class Users::FeedbacksController < ApplicationController
  before_action :set_winner, only: :show

  def index
    @winners = Winner.includes(:user).published.order(id: :desc)
  end

  def show; end

  private

  def set_winner
    @winner = Winner.find(params[:id])
  end
end

app/controllers/users/invite_people_controller.rb
class Users::InvitePeopleController < ApplicationController
  before_action :set_url
  before_action :render_qr_code

  def show; end

  private

  def set_url
    if current_user
      @url="#{request.base_url}/users/sign_up?promoter=#{current_user&.email}"
    else
      @url="#{request.base_url}/users/sign_up"
      end
  end

  def render_qr_code
    qrcode = RQRCode::QRCode.new(@url)
    @svg = qrcode.as_svg(
      color: "000",
      shape_rendering: "crispEdges",
      module_size: 8,
      standalone: true,
      use_path: true
    )
  end
end

app/controllers/users/lotteries_controller.rb
class Users::LotteriesController < ApplicationController
  before_action :authenticate_user!, only: :create
  before_action :set_item, only: :create

  def index
    @items = Item.active.starting
    @items = @items.includes(:category).where(category: { name: params[:category] }) if params[:category].present?
    @categories = Category.all
  end

  def show
    @item = Item.active.starting.find(params[:id])
    @user_bets = @item.bets.where(user: current_user).where(batch_count: @item.batch_count).betting
    @bet = Bet.new
  end

  def create
    if current_user.coins >= params[:bet][:coins].to_i
      begin
        loop_count = params[:bet][:coins].to_i
        params[:bet][:coins] = 1
        params[:bet][:item_id] = @item
        ActiveRecord::Base.transaction do
          loop_count.times do
            @bet = Bet.new(bet_params)
            @bet.item = @item
            @bet.user = current_user
            @bet.batch_count = @item.batch_count
            @bet.save!
          end
        end
        flash[:notice] = "Bet successfully "
      rescue ActiveRecord::RecordInvalid => exception
        flash[:alert] = exception
      end
      redirect_to users_lottery_path(@item)
      else
        flash[:alert] = "Your coins is #{current_user.coins}, it is insufficient for your bet. Buy coins and bet again!"
      redirect_to users_lottery_path(@item)
    end
  end

  private

  def set_item
    @item = Item.find(params[:bet][:item_id])
  end

  def bet_params
    params.require(:bet).permit(:coins, :item_id)
  end
end

app/controllers/users/offers_controller.rb
class Users::OffersController < ApplicationController
  before_action :set_order, only: :order
  before_action :authenticate_user!, only: :order

  def index
    @offers = Offer.active
  end

  def order
    @order = Order.new
    @order.genre = :deposit
    @order.amount = @offer.amount
    @order.coin = @offer.coin
    @order.user = current_user
    @order.offer = @offer
    if @order.save
      if @order.may_submit? && @order.submit!
        flash[:notice] = "Ordered successfully"
      else
        flash[:alert] = "Ordered failed"
        @order.cancel!
      end
      redirect_to users_offers_path
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
      render :index
    end
  end

  private

  def set_order
    @offer = Offer.active.find(params[:offer_id])
  end
end

app/controllers/users/orders_controller.rb
class Users::OrdersController < ApplicationController
  before_action :set_order

  def cancel
    if @order.cancel!
      flash[:notice] = "Cancelled Successfully"
    else
      flash[:alert] = @order.errors.full_messages.join(', ')
    end
    redirect_to users_profile_path
  end

  private

  def set_order
    @order = Order.where(user: current_user).submitted.find(params[:order_id])
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  def show
    @orders = Order.where(user: current_user).order(id: :desc) if params[:records] == 'order' || params[:records].blank?
    @bets = Bet.includes(:item).where(user: current_user).order(id: :desc) if params[:records] == 'bet'
    @winners = Winner.includes(:item, :bet).where(user: current_user).order(id: :desc) if params[:records] == 'winner'
    @invites = User.where(parent: current_user).order(id: :desc) if params[:records] == 'invite'
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
    unless cookies[:promoter]
      cookies[:promoter] = params[:promoter]
    end
  end

  def update
    user=params[:user]
    if user[:current_password].blank? && user[:password_confirmation].blank? && user[:password].blank?
      update_user
    else
      update_password
    end
  end

  def create
    params[:user][:parent_id] = User.find_by_email(cookies[:promoter])&.id
    super
  end

  private

  def sign_up_params
    params.require(:user).permit(:parent_id, :email, :password, :password_confirmation, :current_password)
  end

  def update_password
    if @user.update_with_password(user_password_params)
      flash[:notice] = "Successfully Updated"
      sign_in @user, :bypass => true
      redirect_to users_profile_path
    else
      render :edit
    end
  end

  def update_user
    if @user.update(user_details_params)
      flash[:notice] = "Successfully Updated"
      sign_in @user, :bypass => true
      redirect_to users_profile_path
    else
      render :edit
    end
  end

  def user_details_params
    params.require(:user).permit(:phone, :image, :username)
  end

  def user_password_params
    params.require(:user).permit(:phone, :image, :username, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    user = User.find_for_authentication(email: params[:user][:email])
    if user&.admin? && user&.valid_password?(params[:user][:password])
      flash[:notice] = "You don't have permission"
      redirect_to action: :new
    else
      super
    end
  end
end

app/controllers/users/shares_controller.rb
class Users::SharesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner

  def show; end

  def update
    if @winner.update(winner_params) && @winner.share!
      flash[:notice] = "Shared Feedback Successfully !"
      redirect_to users_profile_path(records: :winner)
    else
      flash[:alert] = @winner.errors.full_messages.join(', ') || 'Failed'
      render :show
    end
  end

  private

  def set_winner
    @winner = Winner.where(user: current_user).delivered.find(params[:id])
  end

  def winner_params
    params.require(:winner).permit(:comment, :picture)
  end
end

app/controllers/users/winners_controller.rb
class Users::WinnersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner
  before_action :set_address, only: :update

  def show; end

  def update
    if @winner.update(address: @address) && @winner.claim!
      flash[:notice] = "Claimed Successfully !"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ') || 'Failed'
    end
    redirect_to users_profile_path(records: :winner)
  end

  private

  def set_winner
    @winner = Winner.where(user: current_user).won.find(params[:id])
  end

  def set_address
    @address = current_user.addresses.find(params[:winner][:address])
  end
end

app/helpers/users/lottery_helper.rb
module Users::LotteryHelper
  def progress(item)
    batch = item.bets.where(batch_count: item.batch_count).betting.count
    minimum_bets = item.minimum_bets
    [(batch/minimum_bets) * 100, 100].min.to_i
  end
end

app/views/users/shared/_carousel.html.erb
<style>
    .marquee-container {
        width: 100%;
        overflow: hidden;
        white-space: nowrap;
    }

    .marquee {
        padding-left: 100%;
        display: inline-block;
        animation: marquee 8s linear infinite;
        animation-play-state: running;
        font-size: 20px;
    }

    .marquee.paused, .marquee-container:hover .marquee {
        animation-play-state: paused;
    }

    @keyframes marquee {
        0% {
            transform: translateX(0);
        }
        100% {
            transform: translateX(-100%);
        }
    }
</style>
<div class="container" style="padding-top:70px">
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% banners.each_with_index do |banner, index| %>
        <div class="carousel-item <%= 'active' if index == 0 %>">
          <%= image_tag banner.preview.url, alt: 'avatar', class: "d-flex w-100" if banner.preview? %>
        </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<section class=" text-light bg-dark" style="height: 4vh;">
    <div class="container">
      <div class="ticker">
        <div class="news">
          <div class="slider">
            <div class="marquee-container">
              <div class="marquee paused">
                <% news_tickers.each do |news_ticker| %>
                  <span><%= news_ticker.content %></span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<script>
    $( document ).ready(function() {
        let key = 0;
        const marquee = $('.marquee');
        $('.marquee span').hide()
        $(".marquee").children().eq(key).show()

        marquee.on('animationiteration', () => {
            key++;
            if (($(".marquee").children().length) == key) key = 0;
            $('.marquee span').hide()
            $(".marquee").children().eq(key).show();
        });

        marquee.removeClass('paused');
    })
</script>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_nav.html.erb
<nav class="navbar navbar-dark bg-dark justify-content-md-end fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: 'navbar-brand text-light' do %>
      <img alt="logo" src="/gelgo.png" style=" height:50px">
    <% end %>
    <ul class="nav ms-auto">
      <% unless user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-white" %>
        </li>
      <% else %>
        <%= link_to users_offers_path, class: "nav-link" do %>
          <li class="nav-item" style="display: inline-block;">
            <div class="d-inline-block mx-2 text-white"><%= current_user.coins %></div>
            <img src="https://www.svgrepo.com/show/227993/coin.svg" , class="d-inline-block" , style="width: 3.5vw; max-width: 16px; position: relative; top:-1px">
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Claim</a>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle link-light" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Language</a>
        <ul class="dropdown-menu " aria-labelledby="navbarDropdown">
          <div class="d-flex justify-content-center">
            <li>
              <%= link_to "English", { :locale => 'en' }, class:"dropdown-item" %>
            </li>
            <li style="border-left: 1px solid gray;">
             <%= link_to "Tagalog", { :locale => 'tl' }, class:"dropdown-item" %>
            </li>
          </div>
        </ul>
      </li>
    </ul>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title">Menu</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <% unless user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Info</a>
            </li>
          <% else %>
            <%= image_tag current_user.image.url, class: "rounded-circle shadow-4", style: "width: 90px;" if current_user.image? %>
            <h4 style="color:Orange;"><b><%= current_user.username %></b></h4>
            <p>Email: <%= current_user.email %></p>
            <p>Coins: <%= current_user.coins %></p>
            </ul>
            <div>
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a class="btn btn-outline-light btn-lg px-5 form-control" href="#">Cash in Now</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Contact Us</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">My Profile</a>
                </li>
                <li class="nav-item">
                  <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", :method => :delete %>
                </li>
          <% end %>
          </ul>
          </div>
          </div>
    </div>
  </div>
</nav>
<nav class="navbar navbar-dark bg-dark justify-content-center fixed-bottom mt-5">
  <ul class="nav">
    <li class="nav-item">
      <%= link_to t('share'), users_feedbacks_path, class: "nav-link", style: "color: darkorange" %>
    </li>
    <li class="nav-item">
      <%= link_to t('invite'), users_invite_people_path, class: "nav-link", style: "color: darkorange" %>
    </li>
    <li class="nav-item">
      <%= link_to t('lottery'), users_lotteries_path, class: "nav-link", style: "color: darkorange" %>
    </li>
    <li class="nav-item">
      <%= link_to t('shop'), users_offers_path, class: "nav-link", style: "color: darkorange" %>
    </li>
    <li class="nav-item">
      <%= link_to t('ako'), users_profile_path, class: "nav-link", style: "color: darkorange" if user_signed_in? %>
    </li>
  </ul>
</nav>