config/routes.rb
Rails.application.routes.draw do
  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    root to: 'home#index'

    namespace :users do
      resource :profile, only: :show
      resource :invite_people, path: 'invite-people', only: :show
      resources :addresses
      resources :lotteries
      resources :offers, path: 'shop', only: :index do
        post :order
      end
      resources :winners, only: [:show, :update]
      resources :shares, only: [:show, :update]
      resources :feedbacks, only: [:show, :index]
      scope  :orders, path: 'orders', as: 'orders' do
        put "cancel/:order_id", to: 'orders#cancel'
      end
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      root to: 'dashboards#index'

      resources :users, only: :index do
        resources :increases, path: 'orders/increase', only: [:new, :create]
        resources :deducts, path: 'orders/deduct', only: [:new, :create]
        resources :bonuses, path: 'orders/bonus', only: [:new, :create]
      end
      resources :items, path: 'items-list', except: :show do
        put :start, :pause, :end, :cancel
      end
      resources :categories, except: :show
      resources :bets, path: 'bets-list', only: :index do
        put :cancel
      end
      resources :winners, path: 'winners-list', only: :index do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers, path: 'offers-list', except: :show
      resources :orders, path: 'orders-list', only: :index do
        put :pay, :cancel
      end
      resources :invites, path: 'invites-list', only: :index
      resources :news_tickers, path: 'news-ticker', except: :show
      resources :banners, path: 'banners-list', except: :show
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @winners = Winner.published.limit(4).order(id: :desc)
    @items = Item.active.starting.limit(9).order(id: :desc)
  end
end

app/views/home/index.html.erb
<%= render "users/shared/nav" %>
<%= render "users/shared/carousel" %>
<div class="container" style="margin-bottom: 100px; margin-top: 15px">
  <h4><%= t('winners_feedback')%></h4>
  <div class="row row-cols-lg-5 d-flex justify-content-center">

    <% @winners.each do |winner| %>
      <%= link_to users_feedback_path(winner), class: "text-decoration-none text-dark" do %>
        <div class=" col d-flex align-self-stretch">
          <div class="card shadow  mb-5 bg-body rounded border-light mt-3 w-100" style="height: 240px">
            <div class="overflow-hidden h-100">
              <%= image_tag winner.picture.url, style: "width: 100%" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    <% if @winners.count == 4 %>
      <%= link_to users_feedbacks_path, class: "text-decoration-none text-dark" do %>
        <div class="card shadow  mb-5 bg-body rounded border-light mt-3 w-100" style="height: 79%">
          <div class="card-body">
            <div style="aspect-ratio: 1 / 1; display: flex; align-items: center; justify-content: center;">See More...
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <h4><%= t('coming_soon')%></h4>
  <div class="row row-cols-lg-5 d-flex justify-content-center">
    <% @items.each do |item| %>
      <div class=" col-md-4 col-4 d-flex align-self-stretch">
        <div class="card shadow  mb-5 bg-body rounded border-light mt-3">
          <div class="card-body d-flex flex-column">
            <div class="overflow-hidden h-100">
              <%= link_to (image_tag item.image.url, class: 'd-block w-100' if item.image?), users_lottery_path(item) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <% if @items.count == 9 %>
      <%= link_to users_lotteries_path, class: "text-decoration-none text-dark" do %>
        <div class="card shadow  mb-5 bg-body rounded border-light mt-3 w-100" style="height: 79%">
          <div class="card-body">
            <div style="aspect-ratio: 1 / 1; display: flex; align-items: center; justify-content: center;">See More...
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>