config/routes.rb
Rails.application.routes.draw do
  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
    root to: 'home#index'

    namespace :users do
      resource :profile, only: :show
      resource :invite_people, path: 'invite-people', only: :show
      resources :addresses
      resources :lotteries
      resources :offers, path: 'shop', only: :index do
        post :order
      end
      resources :winners, only: [:show, :update]
      resources :shares, only: [:show, :update]
      resources :feedbacks, only: [:show, :index]
      scope  :orders, path: 'orders', as: 'orders' do
        put "cancel/:order_id", to: 'orders#cancel'
      end
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      devise_for :users, controllers: { sessions: 'admin/sessions' }
      root to: 'dashboards#index'

      resources :users, only: :index do
        resources :increases, path: 'orders/increase', only: [:new, :create]
        resources :deducts, path: 'orders/deduct', only: [:new, :create]
        resources :bonuses, path: 'orders/bonus', only: [:new, :create]
      end
      resources :items, path: 'items-list', except: :show do
        put :start, :pause, :end, :cancel
      end
      resources :categories, except: :show
      resources :bets, path: 'bets-list', only: :index do
        put :cancel
      end
      resources :winners, path: 'winners-list', only: :index do
        put :submit, :pay, :ship, :deliver, :publish, :remove_publish
      end
      resources :offers, path: 'offers-list', except: :show
      resources :orders, path: 'orders-list', only: :index do
        put :pay, :cancel
      end
      resources :invites, path: 'invites-list', only: :index
      resources :news_tickers, path: 'news-ticker', except: :show
      resources :banners, path: 'banners-list', except: :show
    end
  end
end

app/models/winner.rb
class Winner < ApplicationRecord
  validates  :picture, :comment, presence: true, if: :shared?
  belongs_to :item
  belongs_to :user
  belongs_to :admin, class_name: "User", optional: true
  belongs_to :address, optional: true
  belongs_to :bet

  mount_uploader :picture, ImageUploader

  include AASM
  aasm column: :state do
    state :won, initial: true
    state :claimed, :submitted, :paid, :shipped, :delivered, :shared, :published, :remove_published

    event :claim do
      transitions from: :won, to: :claimed
    end

    event :submit do
      transitions from: :claimed, to: :submitted
    end

    event :pay do
      transitions from: :submitted, to: :paid
    end

    event :ship do
      transitions from: :paid, to: :shipped
    end

    event :deliver do
      transitions from: :shipped, to: :delivered
    end

    event :share do
      transitions from: :delivered, to: :shared
    end

    event :publish do
      transitions from: :shared, to: :published
      transitions from: :remove_published, to: :published
    end

    event :remove_publish do
      transitions from: :published, to: :remove_published
    end
  end
end

app/controllers/admin/winners_controller.rb
class Admin::WinnersController < AdminController
  before_action :set_winner, except: [:index]

  def index
    @winners = Winner.includes(:user, :item, :bet, :address).order(id: :desc)
    @winners = @winners.where(bet: { serial_number: params[:serial_number] }) if params[:serial_number].present?
    @winners = @winners.where(item: { name: params[:product_name] }) if params[:product_name].present?
    @winners = @winners.where(user: { email: params[:email] }) if params[:email].present?
    @winners = @winners.where(state: params[:state]) if params[:state].present?
    @winners = @winners.where(created_at: params[:start].to_datetime..params[:end].to_datetime) if params[:start].present? && params[:end].present?
  end

  def submit
    if @winner.submit!
      flash[:notice] = "Submitted Successfully"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def pay
    if @winner.pay!
      flash[:notice] = "Paid Successfully"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def ship
    if @winner.ship!
      flash[:notice] = "Shipped Successfully"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def deliver
    if @winner.deliver!
      flash[:notice] = "Delivered Successfully"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def publish
    if @winner.publish!
      flash[:notice] = "Published Successfully"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  def remove_publish
    if @winner.remove_publish!
      flash[:notice] = "Remove Published Successfully"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ')
    end
    redirect_to admin_winners_path
  end

  private

  def set_winner
    @winner = Winner.find(params[:winner_id])
  end
end

app/controllers/users/winners_controller.rb
class Users::WinnersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_winner
  before_action :set_address, only: :update

  def show; end

  def update
    if @winner.update(address: @address) && @winner.claim!
      flash[:notice] = "Claimed Successfully !"
    else
      flash[:alert] = @winner.errors.full_messages.join(', ') || 'Failed'
    end
    redirect_to users_profile_path(records: :winner)
  end

  private

  def set_winner
    @winner = Winner.where(user: current_user).won.find(params[:id])
  end

  def set_address
    @address = current_user.addresses.find(params[:winner][:address])
  end
end

app/views/admin/winners/index.html.erb
<%= render "layouts/adnav" %>
<div class="main mt-4">
  <%= render "shared/flash_error" %>
  <div class="card shadow rounded">
    <%= form_tag({ url: admin_winners_path }, { method: :get }) do %>
      <div class="card-header shadow-sm rounded">
        <div class="row">
          <div class="col-8 ">
            <h1 class="mt-1"><b>Winners List</b></h1>
          </div>
          <div class="col-2 ">
            <%= link_to "Reset", admin_winners_path, class: "btn btn-warning col-12 mt-2 shadow-sm rounded" %>
          </div>
          <div class="col-2 ">
            <%= submit_tag :Search, class: "btn btn-primary col-12 mt-2 shadow-sm rounded" %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-4">
            <%= text_field_tag :serial_number, params[:serial_number], placeholder: "Serial Number", class: "form-control shadow-sm rounded" %>
          </div>
          <div class="col-4">
            <%= text_field_tag :email, params[:email], placeholder: "Email", class: "form-control shadow-sm rounded" %>
          </div>
          <div class="col-4">
            <%= select_tag :state, options_for_select(Winner.aasm.states.map(&:name), params[:state]), { prompt: 'State', class: "form-control form-select shadow-sm rounded" } %>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-6">
            <div class="input-group">
              <span class="input-group-text shadow-sm">Start Date</span>
              <%= datetime_field_tag :start, params[:start], class: "form-control shadow-sm" %>
            </div>
          </div>
          <div class="col-6">
            <div class="input-group">
              <span class="input-group-text shadow-sm">End Date</span>
              <%= datetime_field_tag :end, params[:end], class: "form-control shadow-sm" %>
            </div>
          </div>
        </div>
    <% end %>
    </div>
  </div>
  <table class="table table-bordered table-dark table-hover text-center mt-2 shadow rounded" style="font-size: 15px">
    <thead>
    <tr style="vertical-align: middle">
      <th scope="col">Serial Number</th>
      <th scope="col">Email</th>
      <th scope="col">Address</th>
      <th scope="col">Name</th>
      <th scope="col">Contact No.</th>
      <th scope="col">State</th>
      <th scope="col">Created At</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <% if @winners.blank? %>
      <tr class="table-light">
        <td colspan="6"><p> No record found.</p></td>
      </tr>
    <% end %>
    <% @winners.each do |winner| %>
      <tr class="table-light" style="vertical-align: middle">
        <td> <%= winner.bet.serial_number %></td>
        <td><%= winner.user.email %></td>
        <td><%= concat_address(winner.address) %></td>
        <td><%= winner.address&.name %></td>
        <td><%= winner.address&.phone_number %></td>
        <td><%= winner.state %></td>
        <td><%= winner.created_at %></td>
        <td>
          <%= link_to "Submit", admin_winner_submit_path(winner), data: { confirm: 'Are you sure you want to submit?' }, class: "btn btn-primary col-12 shadow-sm rounded", method: :put if winner.may_submit? %>
          <%= link_to "Pay", admin_winner_pay_path(winner), data: { confirm: 'Are you sure you want to pay?' }, class: "btn btn-primary col-12 shadow-sm rounded", method: :put if winner.may_pay? %>
          <%= link_to "Ship", admin_winner_ship_path(winner), data: { confirm: 'Are you sure you want to ship?' }, class: "btn btn-primary col-12 shadow-sm rounded", method: :put if winner.may_ship? %>
          <%= link_to "Deliver", admin_winner_deliver_path(winner), data: { confirm: 'Are you sure you want to deliver?' }, class: "btn btn-primary col-12 shadow-sm rounded", method: :put if winner.may_deliver? %>
          <%= link_to "Publish", admin_winner_publish_path(winner), data: { confirm: 'Are you sure you want to publish?' }, class: "btn btn-primary col-12 shadow-sm rounded", method: :put if winner.may_publish? %>
          <%= link_to "Remove Publish", admin_winner_remove_publish_path(winner), data: { confirm: 'Are you sure you want to remove published?' }, class: "btn btn-danger col-12 shadow-sm rounded", method: :put if winner.may_remove_publish? %>
        </td>
      </tr>
    <% end %>
  </table>
</div>